version: '3'
services:
    hash_generation_backend_prod:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=production
        restart: always
        ports:
            - '8011:8007'
        volumes:
            - server-logs:/app/logs
volumes:
    server-logs:
